### ISSUE TITLE
Adding this to awesome-semantic list?

### ISSUE THREAD

**Issue by douglasg14b** [johnwmcarneiro/vue-contact-manager#1]
Hi

Would you like this project added to the https://github.com/douglasg14b/awesome-semantic-ui list? If so, would you be able to add a "how to" guide to the project (if it's meant to be integrated into others systems)?

**Comment by johnwmcarneiro** [comment]
Of course! It would be nice ;)
I will improve the Readme instructions.
But this project I did to study about Vuex, I will probably make few updates, would I have a problem?
